### ISSUE TITLE
Release Full Code?

### ISSUE THREAD

**Issue by Borororo** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#1]
Hi, thanks for your valuable work!
I notice that the current repo only contains meta-NMN on GQA, so when do you plan to release the full code and models of your work? Can't wait for it :)

**Comment by sjtuytc** [comment]
Hi, thanks for your attention! We are still working on the code release. The model part is almost finished, but the dataset part needs further handling.
