### ISSUE TITLE
Cannot run the codes because of missing files

### ISSUE THREAD

**Issue by TianweiXing** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#10]
@sjtuytc I'm trying to use the "generate_cand_dict" to generate type2can_dict.pkl, but this script is also not runnable... It requires 'mmnm_questions/list_trainval_all_fully.pkl', which does not exist. Also I searched the entire repo, and didn't find any code for generating the "list_trainval_all_fully.pkl".
Could you please provide a way to run the code?

**Comment by sjtuytc** [comment]
Thanks for your attention. As the name shows, the missing dict is just a concatenation of all data of training and validation. There is no magix to generate the dict.

**Comment by TianweiXing** [comment]
Thanks for the reply!
Could you elaborate more? (the "type2can_dict.pkl" is a concatenation of which files?) Or, could you provide the file/codes?

**Comment by sjtuytc** [comment]
All of the original unmodified data. You can download it from the official website of gqa.
