### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by LemonQC** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#2]
您好，能否提供一下您的finetuned的模型，还有您将language转为program的transformer 模型

**Comment by sjtuytc** [comment]
感谢你的关注。时间过去太久了，我现在没存finetuned模型了。至于language转为program，这部分我记得我们就是用的baseline的方法，NMNN，这部分并不是我们的贡献。你可以直接去他们仓库找。

**Comment by LemonQC** [comment]
好的，谢谢您的回复，这是一个很不错的工作，对我们的研究很有启发


| |
Shandong University
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Zelin ***@***.***> |
| 发送日期 | 2022年11月18日 21:58 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks] 关于预训练模型 (Issue #2) |

感谢你的关注。时间过去太久了，我现在没存finetuned模型了。至于language转为program，这部分我记得我们就是用的baseline的方法，NMNN，这部分并不是我们的贡献。你可以直接去他们仓库找。

**Comment by sjtuytc** [comment]
再次感谢你的appreciation，这对我们来讲很重要
