### ISSUE TITLE
About files “type2can_dict.pkl” and “list_train.pkl” 

### ISSUE THREAD

**Issue by vacuum-cup** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#3]
Hello，we can't find the files “type2can_dict.pkl” and "list_train.pkl" , Could you please provide it?

**Comment by sjtuytc** [comment]
They are just caching files, and I think the generating scripts can be found somewhere in this repo.
Sorry, since I have left Gatech, I cannot find these files anymore.

**Comment by sjtuytc** [comment]
You can refer to:
https://github.com/sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks/blob/main/gqa/offline_tools/generate_cand_dict.py

**Comment by TianweiXing** [comment]
@vacuum-cup Did you solve the problem? Running into the same issue here.

@sjtuytc I'm trying to use the "generate_cand_dict" to generate type2can_dict.pkl, but this script is also not runnable... It requires 'mmnm_questions/list_trainval_all_fully.pkl', which does not exist. Also I searched the entire repo, and didn't find and code for generating the "list_trainval_all_fully.pkl".
Could you please provide a way to run the code?
