### ISSUE TITLE
Code about MineCraft experiments.

### ISSUE THREAD

**Issue by LemonQC** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#4]
Can you provide a google driver link for the experiments' code?

**Comment by sjtuytc** [comment]
I can personally offer it to you upon email requests with your name, institution, and purposes. This is because the MineCraft experiments' code is subject to the license of IBM, and we are not to make it publically available.

**Comment by LemonQC** [comment]
ok, I have sent email and thank you again
