### ISSUE TITLE
运行过程中的bug.

### ISSUE THREAD

**Issue by LemonQC** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#5]
执行参数：python run_experiments.py --do_train
按照您的提示，一步步创建pkl文件，但是在gqa_dataset.py的130行，returns = entry[2]，我们发现这个始终是空列表，从而在下面的执行中报错

**Comment by sjtuytc** [comment]
这个是为什么entry[2]为什么是空列表

**Comment by LemonQC** [comment]
> 
您可以检查一下您生成的*inputs.json，第三个参数应该是空列表

**Comment by sjtuytc** [comment]
inputs.json我现在没了，但是我记得没有空列表，为啥会有空列表呢
