### ISSUE TITLE
KL散度计算bug

### ISSUE THREAD

**Issue by LemonQC** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#6]
在KL散度计算的时候，进入的参数尺寸不一致
![image](https://user-images.githubusercontent.com/30914380/203788854-5958b9f8-8488-4fa4-989e-12b853482af4.png)

**Comment by sjtuytc** [comment]
这里的length感觉不太对，你打印出来看看，你数据里的length是什么，然后这里tensor的shape是什么

**Comment by LemonQC** [comment]
![image](https://user-images.githubusercontent.com/30914380/203789864-7e7e9674-ffee-4224-9432-cf094a8480ba.png)
长度都是默认，参数没有修改的49

**Comment by sjtuytc** [comment]
logits那个我看shape是正常的，前面那个错了吧，应该是256*9的才对，就是49的一个分类loss嘛，输入gt肯定是256*9的，为啥你这里能是256呢？我没记错的话这里应该是program吧，一个program能用一个token表示嘛？肯定是九个token呀

**Comment by LemonQC** [comment]
![image](https://user-images.githubusercontent.com/30914380/203799045-742a72e1-c4dd-476b-b812-02d16e900764.png)
这是batch的返回参数，下面是对应的尺寸
![image](https://user-images.githubusercontent.com/30914380/203799226-4cd5d1f5-1ac4-4be2-a96e-d8ac9ffa776a.png)

**Comment by sjtuytc** [comment]
这个【256，9】的才应该是KL_loss的第一项，我不知道为啥你跑出来会错位，但是应该很容易fix，只要看懂程序

**Comment by sjtuytc** [comment]
https://github.com/wenhuchen/Meta-Module-Network/blob/master/run_experiments.py
看这里的327行，这里我们没有改

**Comment by LemonQC** [comment]
> https://github.com/wenhuchen/Meta-Module-Network/blob/master/run_experiments.py 看这里的327行，这里我们没有改

我感觉还是那个列表是空的缘故导致的，但是我也是直接运行的代码生成，下面这行代码生成的时候您是否有修改
https://github.com/wenhuchen/Meta-Module-Network/blob/473fbaa60b66e933d4051fece1a90dac4ecefd09/preprocess.py#L344

**Comment by sjtuytc** [comment]
这个地方没有印象了，但是这个输入数据这块我们应该是没改动的，就跟meta一样应该

**Comment by LemonQC** [comment]
> 

按照作者提供的代码，应该是空的，而且按照下面的思路，应该是数字才对
![image](https://user-images.githubusercontent.com/30914380/203806466-ae27c2c4-19eb-4d99-97c1-1c5969b54336.png)

**Comment by sjtuytc** [comment]
这个是每一步执行结果的gt，这个是空的的话怎么训练呢？

**Comment by LemonQC** [comment]
> 这个是每一步执行结果的gt，这个是空的的话怎么训练呢？

就只能设置为0，去训练，但是现在loss一直是Nan，我感觉还是代码解析那里的问题，您如果还存有一部分中间过程的话可以看看是否也是这样

**Comment by LemonQC** [comment]
下面是meta提供的示例，第三个参数的确是空列表
![image](https://user-images.githubusercontent.com/30914380/203884119-94e8f438-11dc-41de-9acb-7659cc5d013c.png)

**Comment by sjtuytc** [comment]
这个不合理呀，returns[2]是空列表的话，MMNN是怎么跑起来的呢？
<img width="862" alt="image" src="https://user-images.githubusercontent.com/31123348/203885521-49dcc1c8-d3e8-4f80-8b7c-b15a6ca23806.png">

**Comment by sjtuytc** [comment]
如果按你说的，returns[2]为空列表，那么上面的returns[idx][0]必然会报错

**Comment by LemonQC** [comment]
是的，很奇怪，而且您可以看一下他的预处理文件，压根就没有处理scene graph的东西

**Comment by sjtuytc** [comment]
事实上你给的inputs.json跟这里也对不上，这里需要一个数字的序列，就用你的话说，“应该是数字才对”。貌似应该对应你给的inputs.json的倒数第三个。
这不应该，因为MNMM这个工作我当时是smoothly地复现的，基本跑起来没啥问题，可能点数跟他文章稍有不同，但是基本可以复现。

**Comment by LemonQC** [comment]
好的，我再试试看，麻烦您了
