### ISSUE TITLE
Error about gqa file

### ISSUE THREAD

**Issue by blxiaoelong** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#8]
I'm trying to train the model on GQA, but the following error occurs:

`Traceback (most recent call last):
  File "run_experiments.py", line 17, in <module>
    from gqa_dataset import *
  File "/home/mcislab/data1/LXY/Multi_Path/ProTo/gqa/gqa_dataset.py", line 4, in <module>
    from gqa_mnnm_constants import *
  File "/home/mcislab/data1/LXY/Multi_Path/ProTo/gqa/gqa_mnnm_constants.py", line 84, in <module>
    with open('meta_info/GQA_hypernym.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'meta_info/GQA_hypernym.json'`

So how can I get these files? Are they made by codes or downloaded from the url?

**Comment by sjtuytc** [comment]
These files are directly taken from MNMM I remember.

**Comment by TianweiXing** [comment]
What is MNMM? Could you provide a link to it? Thanks
