### ISSUE TITLE
What are the parameters / arguments for reproducing the result in the paper?

### ISSUE THREAD

**Issue by TianweiXing** [sjtuytc/Neurips21-ProTo-Program-guided-Transformers-for-Program-guided-Tasks#9]
Hi, I'm trying to train the model and reproduce the result. But noticed that some details are missing here.
What are the parameters / arguments for reproducing the result in the paper? (e.g.,lr_decrease_start, num_epochs, etc...)
Could you please provide the full training instruction?
Thanks.

**Comment by sjtuytc** [comment]
Thanks for your attention. 
Sorry, I forget the specific training parameters. But it should be okay to use the default training parameters.
Although this would affect several points in terms of precision, this should not affect the major conclusions of this paper.
